import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
result1=np.add(arr1,arr2)
result2=np.subtract(arr1,arr2)
result3=np.multiply(arr1,arr2)
result4=np.divide(arr1,arr2)
result5=np.power(arr1,arr2)
result6=np.mod(arr1,arr2)
result7=np.divmod(arr1,arr2)
print("addition:",result1)
print("sunstraction:",result2)
print("multiplition:",result3)
print("division:",result4)
print("power:",result5)
print("remainder:",result6)
print("quotient and remainder:",result7)